# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -79824177721@yandex.ru
    on_success: never # default: change
    on_failure: always # defa,ult: always
    #env:
      #global:
        - CODECOV_TOKEN="d5ba33c1-60f4-4d78-96f4-2bf42a938cd6"